#!/usr/bin/python
# This file is automatically generated by symbiotic-build.sh

versions = {
	'symbiotic' : 'b34dd3a1a0f6dbcbd17260906eff5702ff64f9aa',
	'dg' : '4b374e5dba6e9a1d76191cd76ae8bad42a977171',
	'sbt-slicer' : '9636fad069d4fdcb03150e287a14887f7b02b2ad',
	'sbt-instrumentation' : 'f07632fdc5ed9c204525c0547ebc6e819746a643',
	'z3' : 'd6df51951f4cdc95f0dfd3b1297d04a465d8f2ca',
	'klee' : 'b71309b475b494cbab3b5580e31bed941dd02687',
}

llvm_version = '10.0.1'

build_types = {
	'symbiotic' : 'Release',
	'dg' : 'Release',
	'sbt-slicer' : 'Release',
	'sbt-instrumentation' : 'Release',
	'z3' : 'Release',
	'klee' : 'Release',
	'klee-runtime' : 'Release',
}

